# Generated by Django 6.1.1 on 2026-09-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=40, null=True),
        ),
    ]
