# Generated by Django 6.1.1 on 2026-09-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_calorieinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorieinfo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bmr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
