# Generated by Django 6.1.1 on 2026-09-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_calorieinfo_date_userinfo_bmr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=40, null=True),
        ),
    ]
