# Generated by Django 6.1.1 on 2026-09-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorieinfo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=40, null=True),
        ),
    ]
