# Generated by Django 6.1.1 on 2026-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_calorieinfo_date_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=40, null=True),
        ),
    ]
