# Generated by Django 6.1.1 on 2026-09-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorieinfo',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
