# Generated by Django 6.1.1 on 2026-09-12 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_user_calorieinfo_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='calorieinfo',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calorieinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=40, null=True),
        ),
    ]
