# Generated by Django 6.1.1 on 2026-09-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_users_userinfo_user_alter_calorieinfo_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='users',
        ),
    ]
