# Generated by Django 6.1.1 on 2026-09-13 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorieinfo',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calorieinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='users',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
